// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJhguCtmY53o3fBZXsJ8UAcSbvzEXPbM',
    appId: '1:983351827742:web:e0f36ed26c5fb6537efd0f',
    messagingSenderId: '983351827742',
    projectId: 'snapsolveai-b74fc',
    authDomain: 'snapsolveai-b74fc.firebaseapp.com',
    storageBucket: 'snapsolveai-b74fc.firebasestorage.app',
    measurementId: 'G-J3Y9NH4B12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLp2fkLLOeIkcXd2LiI3NQwugqgHWNaQ',
    appId: '1:983351827742:android:458c182d126aca5a7efd0f',
    messagingSenderId: '983351827742',
    projectId: 'snapsolveai-b74fc',
    storageBucket: 'snapsolveai-b74fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVXwokWJjnDryoFShF3mrb7SoLxx16fE',
    appId: '1:983351827742:ios:329f4a04114582ed7efd0f',
    messagingSenderId: '983351827742',
    projectId: 'snapsolveai-b74fc',
    storageBucket: 'snapsolveai-b74fc.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
